import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'package:http/http.dart' as http;
import 'package:provider/provider.dart';
import 'package:skripsi/model/models.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:skripsi/main.dart';
part 'Jadwal_services.dart';
part 'notivication_services.dart';
part 'log_services.dart';